AY2425S1-CS2103-F12-2/tp

docs/AboutUs.md, docs/DeveloperGuide.md, docs/UserGuide.md, docs/index.md
Renamed AB-3 with T_Assistant across all site pages, and removed placeholder in AboutUs page.
=> Update site-wide settings using MarkBind

README.md, docs/DeveloperGuide.md, docs/index.md
closes #33.
updated CodeCov and CI badges on AboutUs and Readme
=> Update readme.md and dg

src/main/java/seedu/address/model/group/GroupName.java, src/main/java/seedu/address/model/task/Deadline.java, src/main/java/seedu/address/model/task/Status.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskName.java
closes #61 
Task package is kept in model, instead of group package to accommodate for future expansion, where students can have individual tasks.
=> Add Task class

src/main/java/seedu/address/logic/commands/DeleteStudentFromGroupCommand.java, src/main/java/seedu/address/model/group/exception/GroupNotFoundException.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteStudentFromGroupCommandParserTest.java
1. Add test cases for DeleteStudentFromGroupCommand;
2. Add test cases for DeleteStudentFromGroupCommandParser;
=> Testcase for delete student from group

src/main/java/seedu/address/model/task/Deadline.java, src/main/java/seedu/address/model/task/Status.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskName.java, src/main/java/seedu/address/ui/TaskCard.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/task/DeadlineTest.java, src/test/java/seedu/address/model/task/StatusTest.java, src/test/java/seedu/address/model/task/TaskNameTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TypicalTasks.java
related to #76 
Still need to work on `TestTask`, `TypicalTasks`.
Also updated validator for Deadline to be in line with our decision. `HH:mm` -> `HHmm`
=> Add test cases for components of Task class

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/model/group/UniqueGroupList.java, src/main/java/seedu/address/ui/GroupTaskCard.java, src/main/java/seedu/address/ui/GroupTaskPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/GroupTaskCard.fxml
This is only the function to list a specific group's tasks. Checkstyle and test cases not updated yet.
=> List tasks command

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/task/UniqueTaskList.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Added the function to list all tasks (list_tasks) and also to list all tasks of a group (list_tasks gn/GROUP_NAME).
Checkstyle and test cases not fixed, to be updated soon.
=> List all tasks command

src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java, src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/model/group/UniqueGroupList.java, src/main/java/seedu/address/model/group/exception/GroupNotFoundException.java, src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java, src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/ui/GroupTaskPanel.java, src/main/java/seedu/address/ui/TaskCard.java, src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/group/UniqueGroupListTest.java
=> Re-implement delete group function

src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/ui/GroupCard.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/GroupListCard.fxml, src/main/resources/view/PersonListCard.fxml
=> Update style of student text in list_group and student to include group

src/main/java/seedu/address/model/student/Email.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/student/EmailTest.java, src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Added TaskTest + Fix errant test cases due to update in Email validation

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTaskToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/model/task/Deadline.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedGroup.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/main/java/seedu/address/ui/GroupCard.java, src/main/java/seedu/address/ui/GroupTaskCard.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/resources/view/GroupTaskCard.fxml, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
Still need to update the display for group tasks and task list.
=> Add tasks to group command

src/main/java/seedu/address/ui/HelpWindow.java
=> Update link in help command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/DeleteTaskFromGroupCommand.java, src/main/java/seedu/address/logic/parser/AddTaskToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/DeleteTaskFromGroupCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/ui/GroupCard.java, src/main/java/seedu/address/ui/GroupTaskCard.java, src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
Create DeleteTaskFromGroupCommand class, its Parser class, and fix checkstyle issues
=> Implement delete a task from group feature

src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
=> Add basic test cases for Delete Group Command

src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java, src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/ListTaskCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/GroupTaskCard.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java, src/test/java/seedu/address/model/student/StudentTest.java, src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
closes #99.
1. Updates to Student and JSONSerializablePerson classes to use Optional<GroupName> instead of Optional<Group>.
2. Also update to loading from JSON when opening the application.
3. And fixed any issues introduced by point 1.
=> Update Save/Load feature + Student Class

src/main/java/seedu/address/logic/Messages.java
=> Remove extra [] that appears in result

src/main/java/seedu/address/logic/commands/DeleteTaskFromGroupCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/GroupTaskCard.java
Create a MarkTaskCommand class and a MarkTaskCommandParser class, and fix checkstyle issues and bugs in the feature.
=> Implement Mark Task feature

src/main/java/seedu/address/logic/commands/AddGroupCommand.java, src/main/java/seedu/address/logic/commands/AddStudentCommand.java, src/main/java/seedu/address/logic/commands/AddStudentToGroupCommand.java, src/main/java/seedu/address/logic/commands/AddTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java, src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java, src/main/java/seedu/address/logic/commands/DeleteStudentFromGroupCommand.java, src/main/java/seedu/address/logic/commands/DeleteTaskFromGroupCommand.java, src/main/java/seedu/address/logic/commands/ListGroupCommand.java, src/main/java/seedu/address/logic/commands/ListStudentCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/commands/MarkTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/LogicManagerTest.java
closes #132 
Additionally make `MESSAGE_USAGE` more uniform across classes
=> Update COMMAND_WORD and Add COMMAND_WORD_ALIAS

build.gradle
=> Enable assertions and import FuzzyWuzzy

src/main/java/seedu/address/model/group/GroupName.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
Additionally allowed hyphens in GroupName to suit naming convention in CS2103
closes #161
=> Update SampleDataUtil to suit our current data format

.gitignore, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/editcommands/EditGroupCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditStudentCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditTaskCommandParser.java, src/test/java/seedu/address/logic/parser/EditGroupCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
Fix the bug for input with missing fields in the edit group function.
Fix bug for input containing invalid prefixes for edit functions.
=> Bug fix for edit functions

src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java, src/main/java/seedu/address/logic/commands/listcommands/ListStudentCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/FindStudentCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindStudentCommandParserTest.java, src/test/java/seedu/address/model/student/StudentMatchesKeywordPredicateTest.java
=> Add Find Student Command + Test Cases

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/findcommands/FindGroupCommand.java, src/main/java/seedu/address/logic/commands/findcommands/FindStudentCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/findcommands/FindGroupCommandParser.java, src/main/java/seedu/address/model/group/GroupName.java, src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java, src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java, src/test/java/seedu/address/model/group/GroupNameContainsKeywordsPredicateTest.java
Currently created but might look into enhancing as it does not accept keywords with spaces in between.
closes #139
=> Add FindGroupCommand + test cases

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/findcommands/FindTaskCommand.java, src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/findcommands/FindTaskCommandParser.java, src/main/java/seedu/address/model/task/TaskName.java, src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java, src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java, src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/testutil/TypicalTasks.java
closes #140 
closes #170 - added missing `model.updateFilteredTaskList(Model.PREDICATE_SHOW_ALL_TASKS)`
=> Add find task command + test cases

src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/student/StudentMatchesQueryPredicate.java, src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
Additionally, updated `MATCH_RATIO` and other ratio methods used in predicate classes.
=> Fix LOD errors

src/main/java/seedu/address/logic/parser/AddressBookParser.java
=> Update command word matching to be case-insensitive

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToAllGroupsCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyUserPrefs.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Not sure if there are bugs
Testing, checkstyle, and documentation to be updated later
=> Add tasks all groups

src/main/java/seedu/address/logic/commands/addcommands/AddStudentCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java, src/main/java/seedu/address/model/student/Email.java, src/main/java/seedu/address/model/student/StudentNumber.java
- Allow case insensitive input for email and student number 
- Edit success messages for sort commands to include how the items (group, student, task) are sorted
- Edit message usage for add student command to make sno prefix first
=> Allow case insensitive input and edit command messages

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java, src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortGroupCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortStudentCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java, src/main/java/seedu/address/logic/parser/addcommands/AddGroupCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddStudentCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToAllGroupsCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentFromGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskFromGroupCommandParser.java, src/main/java/seedu/address/logic/parser/listcommands/ListTaskCommandParser.java, src/main/java/seedu/address/model/AddressBook.java
Fixed a couple of bugs. Refer to all linked issues.
=> Fix bugs alpha bugs

docs/UserGuide.md
- Added extraneous prefix throws error
- Added shorthands
=> Update Command notes

src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/group/GroupName.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/task/Deadline.java
closes #264 - update deadline error message
closes #268 - improve GroupName parsing
closes #266 - make tags case-insensitive
=> 20241105 Fix bugs + enhancements

docs/DeveloperGuide.md, docs/UserGuide.md, docs/_markbind/layouts/default.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/LogicClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UiClassDiagram.puml
closes #275 
closes #276 
closes #277 
closes #278 
closes #296
closes #297
=> Update UG and DG

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/addcommands/AddStudentToGroupCommand.java, src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java, src/main/java/seedu/address/model/student/Email.java, src/main/java/seedu/address/model/student/Name.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/model/student/StudentNumber.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/java/seedu/address/model/student/EmailTest.java, src/test/java/seedu/address/model/student/StudentTest.java
Closes #261 
Closes #261 
Closes #262 
Closes #288
=> Update input validation and command parameters

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/listcommands/ListTaskCommand.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java
closes #307 
Also fixed formatting issues
=> 20241107 documentation updates

src/main/java/seedu/address/logic/commands/editcommands/EditGroupCommand.java
=> Fix edit group not updating student's group name

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/editcommands/EditTaskAllGroupCommand.java, src/main/java/seedu/address/logic/commands/editcommands/EditTaskCommand.java, src/main/java/seedu/address/logic/commands/markcommands/MarkTaskCommand.java, src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/model/task/Task.java, src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java, src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteStudentFromGroupCommandTest.java
Fixed setTask method needing index
> can be supplied with incorrect index when used in EditTaskAll
=> Documentation changes and bug fix

docs/DeveloperGuide.md, docs/UserGuide.md
closes #397  
closes #396 
closes #345 
closes #344 
closes #402 
closes #400 
closes #399 
closes #393 
closes #387 
closes #386 
closes #384 
closes #380 
closes #363 
closes #362 
closes #360
=> 20241110 ug updates

docs/DeveloperGuide.md, docs/UserGuide.md
Closes #355 
Closes #365 
Closes #374 
Closes #378 
Closes #381 
Closes #385 
Closes #391 
Closes #351 
Closes #352 
Closes #401 
Closes #303 
Closes #379 
Closes #405
=> Updates on DG and UG

docs/DeveloperGuide.md
- update use cases for find students, groups and tasks commands;
- update use cases for edit student, group, task for all group and task for specific group commands.
=> Add use cases in DG

docs/UserGuide.md
=> Add in explanation for editing a group

docs/DeveloperGuide.md, docs/diagrams/ModelClassDiagram.puml
=> Improve layout of model class diagram

docs/UserGuide.md
=> Add where to get index for commands that use index

src/main/java/seedu/address/logic/commands/editcommands/EditStudentCommand.java
=> Fix bug for not throwing error message for duplicated email

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/parser/addcommands/AddExistingTaskToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddGroupCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddStudentCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddStudentToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToAllGroupsCommandParser.java, src/main/java/seedu/address/logic/parser/addcommands/AddTaskToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteStudentFromGroupCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskForAllGroupsCommandParser.java, src/main/java/seedu/address/logic/parser/deletecommands/DeleteTaskFromGroupCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditGroupCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditStudentCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditTaskAllGroupCommandParser.java, src/main/java/seedu/address/logic/parser/editcommands/EditTaskCommandParser.java, src/main/java/seedu/address/logic/parser/findcommands/FindGroupCommandParser.java, src/main/java/seedu/address/logic/parser/findcommands/FindStudentCommandParser.java, src/main/java/seedu/address/logic/parser/findcommands/FindTaskCommandParser.java, src/main/java/seedu/address/logic/parser/listcommands/ListTaskCommandParser.java, src/main/java/seedu/address/logic/parser/markcommands/MarkTaskCommandParser.java
closes #359 
- Removed all extra prefix checks in parser classes
- Added text in UG
- Removed effort portion of DG
=> Extraneous parameter check removal

src/main/java/seedu/address/logic/commands/addcommands/AddExistingTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/addcommands/AddTaskToAllGroupsCommand.java, src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java, src/main/java/seedu/address/logic/commands/deletecommands/DeleteTaskForAllGroupsCommand.java, src/main/java/seedu/address/logic/commands/findcommands/FindTaskCommand.java, src/main/java/seedu/address/logic/commands/sortcommands/SortTaskCommand.java, src/main/java/seedu/address/logic/commands/versionhistorycommands/RedoCommand.java, src/main/java/seedu/address/logic/commands/versionhistorycommands/UndoCommand.java
Turns out it was a GUI problem
=> Fix group display add all tasks
